<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE program [
<!ELEMENT program (tac+)>
<!ELEMENT tac (dst?,src1?,src2?)>
<!ELEMENT dst (#PCDATA)>
<!ELEMENT src1 (#PCDATA)>
<!ELEMENT src2 (#PCDATA)>
<!ATTLIST program name CDATA #IMPLIED>
<!ATTLIST tac opcode CDATA #REQUIRED>
<!ATTLIST tac order CDATA #REQUIRED>
<!ATTLIST dst type (integer|string|variable|label) #REQUIRED>
<!ATTLIST src1 type (integer|string|variable) #REQUIRED>
<!ATTLIST src2 type (integer|string|variable) #REQUIRED>
<!ENTITY language "IPPeCode">
<!ENTITY eol "&#xA;">
<!ENTITY gt ">">
<!ENTITY lt "<">
]>
<program name="Simple example of a program in IPPeCode">
<tac opcode="MOV" order="1">
<dst type="variable">counter</dst>
<src1 type="integer">0</src1>
</tac>
<tac opcode="READSTR" order="2">
<dst type="variable">Input</dst>
</tac>
<tac opcode="LABEL" order="3">
<dst type="label">@WHILE_</dst>
</tac>
<tac opcode="JUMPIFEQ" order="4">
<dst type="label">@End</dst>
<src1 type="variable">counter</src1>
<src2 type="integer">+3</src2>
</tac>
<tac opcode="PRINT" order="5">
<src1 type="variable">Input</src1>
</tac>
<tac opcode="PRINT" order="6">
<src1 type="string">&eol</src1>
</tac>
<tac opcode="ADD" order="7">
<dst type="variable">counter</dst>
<src1 type="variable">counter</src1>
<src2 type="integer">1</src2>
</tac>
<tac opcode="JUMP" order="8">
<dst type="label">@WHILE_</dst>
</tac>
<tac opcode="LABEL" order="9">
<dst type="label">@End</dst>
</tac>
</program>